---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 24.11.2021 19:59
---
function EffectFromUnit2Unit(effModel, hero,enemy)
    local x,y=GetUnitXY(enemy)
    local xEnd,yEnd=GetUnitXY(hero)
    local z = 80
    local eff = AddSpecialEffect(effModel, x, y)
    BlzSetSpecialEffectPosition(eff, x, y, z)
    local angle = AngleBetweenXY(x, y, xEnd, yEnd)/ bj_DEGTORAD
    local angleFake = angle - 45
    --BlzSetSpecialEffectScale(eff, 0.1)
    local d=0
    TimerStart(CreateTimer(), TIMER_PERIOD64, true, function()
        d=d+1
        angleFake = angleFake + 7
        angle = AngleBetweenXY(x, y, xEnd, yEnd)/ bj_DEGTORAD
        x, y = MoveXY(x, y, 20,  angle)
        BlzSetSpecialEffectPosition(eff, x, y, z)
        --BlzSetSpecialEffectScale(eff, 0.1)
        xEnd,yEnd=GetUnitXY(hero)
        if DistanceBetweenXY(x, y, xEnd, yEnd) <= 50 or d>=100 then
            DestroyTimer(GetExpiredTimer())
            DestroyEffect(eff)
            local gain=BlzGetUnitMaxHP(enemy)/100
            if gain<1 then
                gain=1
            end
            UnitAddGold(hero,R2I(gain))
            --print("долетел")
        end
    end)
end