---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 19.12.2021 0:20
---

BDItems = {
    ["Slime Card"]  = {
        descriptions = "Постоянное увеличение ХП на 50",
        effModel     = "SpecialItemWhite",
        ico          = "card",
        cost         = "100",
        lvl          = 1,
        short        = "HP UP",
        drop         = 5,
    },
    ["Slime Jelly"] = {
        descriptions = "Исцеляет на 50 единиц при подборе",
        effModel     = "",
        ico          = "ReplaceableTextures\\CommandButtons\\BTNPhilosophersStone.blp",
        cost         = "100",
        lvl          = 1,
        short        = "Heal",
        drop         = 50,
    },
    ["Slime Egg"]   = {
        descriptions = "Слайм всегда сражается на вашей стороне",
        effModel     = "",
        ico          = "ReplaceableTextures\\CommandButtons\\BTNPhoenixEgg.blp",
        cost         = "100",
        lvl          = 1,
        short        = "Summon Slime",
        drop         = 20,
    },
    ["Apple"]       = {
        descriptions = "Восстанавливает 10 здоровья",
        effModel     = "",
        ico          = "Icons\\RO\\apple",
        cost         = "100",
        lvl          = 1,
        short        = "Small Heal",
        drop         = 20,
    },
}