---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 19.12.2021 0:20
---

BDItems = {
    ["SlimeCard"] = {
        descriptions = "Карта из самого слайма, что-то может делать",
        ico          = "ReplaceableTextures\\CommandButtons\\BTNDust",
        cost         = "100",
        lvl          = 1,
    },
}