---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 18.12.2021 22:35
---
function CatchItem(data)
    --local tempTable = AllItemsTable
    for i = 1, #AllItemsTable do
        if i<=#AllItemsTable then
            --print(i,#AllItemsTable)
            local dataItems = AllItemsTable[i]
            local x, y = dataItems[3], dataItems[4]
            local d = DistanceBetweenXY(x, y, GetUnitXY(data.UnitHero))
            if d <= 150 then
                if AddItem2Hero(data,dataItems[2]) then
                    DestroyEffect(AddSpecialEffect("Abilities\\Spells\\Human\\HolyBolt\\HolyBoltSpecialArt", x, y))
                    DestroyEffect(dataItems[1])
                    table.remove(AllItemsTable, i)
                end
                --приходится обрывать цикл чтобы не было проблем
                break
            end
        end
    end
   -- AllItemsTable = tempTable
end