---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 18.12.2021 19:35
---
function InitInventory(data)
    local BoxFrame = CreateInventoryBox(data)
    CreateInventoryButton(data, nil, BoxFrame)
end
function CreateInventoryButton(data, texture, BoxFrame)
    if not texture then
        texture = "ReplaceableTextures\\CommandButtons\\BTNDust.blp"
    else

    end
    local SelfFrame = BlzCreateFrameByType('GLUEBUTTON', 'FaceButton', BlzGetOriginFrame(ORIGIN_FRAME_GAME_UI, 0), 'ScoreScreenTabButtonTemplate', 0)
    local buttonIconFrame = BlzCreateFrameByType('BACKDROP', 'FaceButtonIcon', SelfFrame, '', 0)

    BlzFrameSetParent(SelfFrame, BlzGetFrameByName("ConsoleUIBackdrop", 0))
    BlzFrameSetParent(buttonIconFrame, BlzGetFrameByName("ConsoleUIBackdrop", 0))


    --BlzFrameSetVisible(SelfFrame, false)
    -- BlzFrameSetVisible(SelfFrame, GetLocalPlayer() == player)
    BlzFrameSetAllPoints(buttonIconFrame, SelfFrame)
    BlzFrameSetTexture(buttonIconFrame, texture, 0, true)
    BlzFrameSetSize(SelfFrame, GNext, GNext)
    BlzFrameSetAbsPoint(SelfFrame, FRAMEPOINT_CENTER, 0.8+GNext/2, GNext/2)

    local ClickTrig = CreateTrigger()
    BlzTriggerRegisterFrameEvent(ClickTrig, SelfFrame, FRAMEEVENT_CONTROL_CLICK)
    TriggerAddAction(ClickTrig, function()
        if BlzFrameIsVisible(BoxFrame) then
            BlzFrameSetVisible(BoxFrame, false)
        else
            BlzFrameSetVisible(BoxFrame, true)
        end

        BlzFrameSetEnable(BlzGetTriggerFrame(), false)
        BlzFrameSetEnable(BlzGetTriggerFrame(), true)

    end)

    local TrigMOUSE_ENTER = CreateTrigger()
    BlzTriggerRegisterFrameEvent(TrigMOUSE_ENTER, SelfFrame, FRAMEEVENT_MOUSE_ENTER)

    TriggerAddAction(TrigMOUSE_ENTER, function()

        --print("показать подсказку ",flag)
        --callENTER()

        --  BlzFrameSetAbsPoint(ttBox, FRAMEPOINT_CENTER, 0, GHandY)


    end)
    local TrigMOUSE_LEAVE = CreateTrigger()
    BlzTriggerRegisterFrameEvent(TrigMOUSE_LEAVE, SelfFrame, FRAMEEVENT_MOUSE_LEAVE)
    TriggerAddAction(TrigMOUSE_LEAVE, function()

        --print("убрать подсказку")
        --callLEAVE()
        --  BlzFrameSetVisible(ttBox, false)
        --BlzFrameSetVisible(tt[1],false)
    end)
    return SelfFrame, buttonIconFrame
end

function CreateInventoryBox(data)
    local x, y = 0.624, 0.175+GNext
    local BoxFrame = BlzCreateFrameByType('BACKDROP', 'FaceButtonIcon', BlzGetOriginFrame(ORIGIN_FRAME_GAME_UI, 0), '', 0)
    local m=1

    for k = 1, 5 do
        for i = 1, 5 do
            data.ItemSlot[m],data.ItemSlotTexture[m],data.ItemSlotName[m]=CreateEmptySlot(data, x + (k - 1) * GNext, y - (i - 1) * GNext, BoxFrame)
            m=m+1
        end
    end
    return BoxFrame
end
GNext = 0.039
function CreateEmptySlot(data, x, y, BoxFrame)
    local empty = "empty_slot"
    local SelfFrame = BlzCreateFrameByType('GLUEBUTTON', 'FaceButton', BoxFrame, 'ScoreScreenTabButtonTemplate', 0)
    local buttonIconFrame = BlzCreateFrameByType('BACKDROP', 'FaceButtonIcon', SelfFrame, '', 0)
    BlzFrameSetParent(SelfFrame, BlzGetFrameByName("ConsoleUIBackdrop", 0))
    BlzFrameSetParent(buttonIconFrame, BlzGetFrameByName("ConsoleUIBackdrop", 0))
   -- BlzFrameSetVisible(SelfFrame, false)
    -- BlzFrameSetVisible(SelfFrame, GetLocalPlayer() == player)
    BlzFrameSetAllPoints(buttonIconFrame, SelfFrame)
    BlzFrameSetTexture(buttonIconFrame, empty, 0, true)
    BlzFrameSetSize(SelfFrame, GNext, GNext)
    BlzFrameSetAbsPoint(SelfFrame, FRAMEPOINT_CENTER, x, y)
    return SelfFrame,buttonIconFrame,empty
end


function GetFrameFreeSlot(data,name)
    local find=false
    for i=1,#data.ItemSlot do
        if data.ItemSlotName[i]=="empty_slot" then
            --print("найден пустой слот в позиции",i)
            data.ItemSlotName[i]=name
            find=true
            return data.ItemSlotTexture[i]
        end
    end
    if not find then
        return false
    end
end