---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 18.12.2021 21:48
---
AllItemsTable={}
function CreateItemPrefab(x,y,name)
    local t={}
    local eff=AddSpecialEffect("SpecialItemWhite",x,y)
    table.insert(t,eff)
    table.insert(t,name)
    table.insert(t,x)
    table.insert(t,y)
    table.insert(AllItemsTable,t)
end