---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 16.12.2021 15:45
---
---Abilities\Spells\Other\CrushingWave\CrushingWaveDamage.mdl
function CastWave(data, x, y, x2, y2)
    local z = GetTerrainZ(x, y)
    --local eff = AddSpecialEffect("Abilities\\Spells\\Other\\CrushingWave\\CrushingWaveMissile.mdl", x, y)
    local angle = AngleBetweenXY(x, y, x2, y2) / bj_DEGTORAD
    local d = DistanceBetweenXY(x, y, x2, y2)
    local speed = d * TIMER_PERIOD64
    --print(speed,d)
    local curDist = 0
    local eff = AddSpecialEffect("Abilities\\Spells\\Other\\CrushingWave\\CrushingWaveMissile.mdl", x, y)
    TimerStart(CreateTimer(), TIMER_PERIOD64, true, function()
        --
        local vector = Vector:new(x, y, z)
        local newVector = vector
        newVector = VectorSum(newVector, vector:yawPitchOffset(speed, angle * (math.pi / 180), 0.0))
        x, y = newVector.x, newVector.y
        BlzSetSpecialEffectPosition(eff, x, y, z)
        BlzSetSpecialEffectYaw(eff, math.rad(angle))
        BlzPlaySpecialEffect(eff, ANIM_TYPE_BIRTH)
        local is, enemy = UnitDamageArea(data.UnitHero, 5, x, y, 200)
        if is then
            DestroyEffect(AddSpecialEffect("Abilities\\Spells\\Other\\CrushingWave\\CrushingWaveDamage.mdl", GetUnitXY(enemy)))
        end
        UnitAddForceSimple(enemy, angle, speed, 100)
        --BlzSetSpecialEffectPosition(eff, newVector.x, newVector.y, z + 50)
        curDist = curDist + speed
        if curDist > d - 150 then
            -- print("конец волны")
            DestroyTimer(GetExpiredTimer())
            DestroyEffect(eff)
        end
    end)
end