---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 14.12.2021 18:24
---
function ChkCrossBad(data, x1, y1, x2, y2, x3, y3, x4, y4)
    local q, sn, fn, n

    if (y2 - y1 ~= 0) then
        q = (x2 - x1) / (y1 - y2)
        sn = (x3 - x4) + (y3 - y4) * q
        fn = (x3 - x1) + (y3 - y1) * q
        n = fn / sn
    else
        n = (y3 - y1) / (y3 - y4)
    end
    local x = x3 + (x4 - x3) * n
    local y = y3 + (y4 - y3) * n
    print("All OK")
    DestroyEffect(AddSpecialEffect("Abilities\\Spells\\Human\\HolyBolt\\HolyBoltSpecialArt", x, y))
    data.line2 = nil
    data.line1 = nil

    if math.abs(math.sqrt(math.sqr(x1 - x3) + math.sqr(y1 - y3)) + math.sqrt(math.sqr(x2 - x3) + math.sqr(y2 - y3)) - math.sqrt(math.sqr(x2 - x1) + math.sqr(y2 - y1))) < 0.1 then
        print('Принадлежит')
    end

    return 1
end

function ChkCross (data, x1, y1, x2, y2, x3, y3, x4, y4)
    --local angle=AngleBetweenXY()


    local s1 = { x = x1, y = y1 }
    local e1 = { x = x2, y = y2 }
    local s2 = { x = x3, y = y3 }
    local e2 = { x = x4, y = y4 }
    local d = (s1.x - e1.x) * (s2.y - e2.y) - (s1.y - e1.y) * (s2.x - e2.x)
    local a = s1.x * e1.y - s1.y * e1.x
    local b = s2.x * e2.y - s2.y * e2.x
    local x = (a * (s2.x - e2.x) - (s1.x - e1.x) * b) / d
    local y = (a * (s2.y - e2.y) - (s1.y - e1.y) * b) / d
    local maxX = math.max(s1.x, s2.x, e1.x, e2.x)
    local minX = math.min(s1.x, s2.x, e1.x, e2.x)
    local maxY = math.max(s1.y, s2.y, e1.y, e2.y)
    local minY = math.min(s1.y, s2.y, e1.y, e2.y)
    if x > maxX or x < minX then
        return false
    end
    if y > maxY or y < minY then
        return false
    end
    local d1 = DistanceBetweenXY(x1, y1, x2, y2)
    local d2 = DistanceBetweenXY(x3, y3, x4, y4)
    local d1x = DistanceBetweenXY(x1, y1, x, y)
    local d2x = DistanceBetweenXY(x3, y3, x, y)
    if d1x > d1 then
        -- print("далеко1")
        return false
    end
    if d2x > d2 then
        --print("далеко2")
        return false
    end
    --print(x, y)
    local v1 = GetVectorFromPoint2D(x1, y1, x2, y2)
    local v2 = GetVectorFromPoint2D(x3, y3, x4, y4)
    local angle = math.deg(v1:angleBetween(v2))
    print(angle)
    CrossCast(data, x, y)
    --return x, y
end

function CrossCast(data, x, y)
    DestroyTimer(data.TimerLineDelay)
    data.line2 = nil
    data.line1 = nil
    DestroyEffect(AddSpecialEffect("Objects\\Spawnmodels\\Undead\\UndeadBlood\\UndeadBloodAbomination.mdl", x, y))
    local _, unit = UnitDamageArea(data.UnitHero, 500, x, y, 150)
    SetUnitExploded(unit, true)
end