---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 30.12.2021 1:51
---
function ChkStoneForGolem(data, xs, ys, r)
    local k = #AllRocks
    local m = 0
    if k > 0 then
        while true do
            --print(i,#AllItemsTable)
            local eff = AllRocks[k]
            local x, y = BlzGetLocalSpecialEffectX(eff),BlzGetLocalSpecialEffectY(eff)
            local d = DistanceBetweenXY(x, y, xs, ys)
            if d <= r then
                m = m + 1
                --print(m)
                DestroyEffect(eff)
                DelayRemoveEarthStrike(eff,0.1)
                table.remove(AllRocks, k)
                if m>=5 then
                    print("каменный голем")
                    return true
                end
                --приходится обрывать цикл чтобы не было проблем
            end
            k = k - 1
            if k <= 0 then
                --  print("перебор предметов окончен")
                break
            end
        end
    end
    return false
end