---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 13.12.2021 1:23
---
function FlameStrike(data, x, y)
    local r=GetRadiusCircle(data, x, y)
    UnitDamageArea(data.UnitHero, r/2, x, y, r)
    local interval=0.1
    local eff=AddSpecialEffect("Abilities\\Spells\\Human\\FlameStrike\\FlameStrike.mdl",x,y)
    local sec=3
    TimerStart(CreateTimer(), interval, true, function()
        sec=sec-interval
        UnitDamageArea(data.UnitHero, r/40, x, y, r)
        if sec<=0 then
            DestroyEffect(eff)
            DestroyTimer(GetExpiredTimer())
        end
    end)
end

function GetRadiusCircle(data, x, y)
    local r = 0
    for i = 1, #data.Points do
        r = r + DistanceBetweenXY(x, y, data.Points[i].x, data.Points[i].y)
    end
    r = r / #data.Points
    return r
end