---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 21.12.2021 3:05
---
function TriggerCastByName(data, nameCast)
    for i = 1, #data.SpellsName do
        if data.SpellsName[i] == nameCast then
            print(nameCast)

            local fh = data.SpellsFH[i]
        end
    end
end

function GetFramePositionsByName(data, nameCast)

end