---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 16.12.2021 21:48
---
function CreateDownInterface(data)
    AddDownInterfaceElement(data,"line")
    AddDownInterfaceElement(data,"circle")
    AddDownInterfaceElement(data,"curve")
    AddDownInterfaceElement(data,"triangle")
    AddDownInterfaceElement(data,"wave")
    AddDownInterfaceElement(data,"squae")
    AddDownInterfaceElement(data,"smallrocks")
    AddDownInterfaceElement(data,"circleHeal")
    AddDownInterfaceElement(data,"clock")
    AddDownInterfaceElement(data,"icewall")
    AddDownInterfaceElement(data,"deathcross")
    AddDownInterfaceElement(data,"grandcross")
    AddDownInterfaceElement(data,"z")
    AddDownInterfaceElement(data,"m")
    AddDownInterfaceElement(data,"сurvecircle")
    AddDownInterfaceElement(data,"golem")

end

function AddDownInterfaceElement(data, name)
    local step = 0.039
    if not data.nextElement then
        data.nextElement = 0
        data.SpellsName={}-- таблица содержит фреймы
        data.SpellsFH={}
    end
    data.nextElement = data.nextElement + 1
    data.SpellsName[data.nextElement]=name
    data.SpellsFH[data.nextElement]=CreateSimpleFrameGlue(data.nextElement*step, 0.02, name)
end