---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 01.12.2021 19:01
---
---
---

function VectorSubtract(vector1, vector2)
    return Vector:new(vector1.x-vector2.x, vector1.y-vector2.y, vector1.z-vector2.z)
end

function InitInputHandler ()

    local nimValueToExtend = 1/8 * 128
    Points = { }

    function ClearPoints() Points = { }  end

    function InputUpdate ()
        local vector = Vector:new(GetPlayerMouseX[0], GetPlayerMouseY[0], 0)

        if HERO[0].LMBIsPressed then
            --print(#Points,Points[#Points])
            if (#Points > 0 and
                    DistanceBetweenXY(GetPlayerMouseX[0], GetPlayerMouseY[0], Points[#Points].x, Points[#Points].y) < nimValueToExtend) then
                return
            end
            table.insert(Points, vector)
            --print("insert OK")

            CreateTMPEffect(GetPlayerMouseX[0], GetPlayerMouseY[0])

            ShapeDetectorAdd(#Points <= 1 and Vector:new(0, 0, 0) or VectorSubtract(vector, Points[#Points - 1]),
                    #Points <= 2 and Vector:new(0, 0, 0) or VectorSubtract(Points[#Points - 1], Points[#Points - 2]),Points)
        end
    end
end