---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 01.12.2021 19:34
---
---

sides = {}
previousDirection = 0

function Distance(vector1, vector2)
    return DistanceBetweenXY(vector1.x, vector1.y, vector2.x, vector2.y)
end

function DetectShape()
    sum = 0
    for i = 1, #angles do
        sum = sum + angles[i]
    end

    for i = 1, #Shapes do
        if (Shapes[i]:check(sum, angles, sides)) then
            return
        end
    end
end

function ShapeDetectorAdd(current, previous)

    if (current == 0 or previous == 0) then return end

    local sensitivity = 15 -- degrees
    local minimumDistanceForSide = 1 * 128

    local direction = VectorSubtract(current, previous)

    if (previousDirection == 0) then
        table.insert(sides, Side:new(current))
        previousDirection = direction
    else
        local angle = math.deg(direction:differenceRegardingUp(previousDirection))

        if (angle < sensitivity) then
            sides[#sides]:changeEnd(current)
        else
            if (sides[#sides]:length() > minimumDistanceForSide) then
                table.insert(sides, Side:new(current))
            else
                sides[#sides] = Side:new(current)
            end
                previousDirection = direction
        end
    end
end

function ShapeDetectorClear()
    local center = Vector:new(0,0,0)
    for i = 1, #Points do
        center.x = center.x + Points[i].x
        center.y = center.y + Points[i].y
    end
    center.x = center.x / #Points
    center.y = center.y / #Points
    DestroyEffect(CreateTMPEffect(center.x, center.y, "Abilities\\Spells\\Human\\HolyBolt\\HolyBoltSpecialArt"))

    for i = 1, 20 do
        --print("  ")
    end

    for i = 1, #sides do
        --print(i.. ". ( ".. sides[i].start.x.. ", ".. sides[i].start.x.. " ) ; (".. sides[i].en.x.. ", ".. sides[i].en.y.. ")")
    end

    -- angles
    angles = { }
    function getAngle(i, j)
        return math.deg(sides[i]:getVector():angleBetween(sides[j]:getVector()))
    end

    for i = 1, #sides do
        if (i < #sides) then
            table.insert(angles, getAngle(i, i + 1))
        else
            table.insert(angles, getAngle(1, #sides))
        end
    end

    anglePrint = ""
    for i = 1, #angles do
        anglePrint = anglePrint .. "; " .. i .. " - " .. angles[i]
    end
   -- print(anglePrint)
    --print("Count: ".. #Points)

    -- clearEffects
    for i = 1, #Effects do
        DestroyEffect(Effects[i])
    end

    DetectShape()

    sides = {}
    previousDirection = 0
end